# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyGww4YNDCdLEN-0nFNbbzViYm5nk6R6
"""



import streamlit as st
import pandas as pd
import joblib
import os

# Definir la ruta base donde se encuentran los archivos joblib
# Asegúrate de que esta ruta sea accesible desde donde ejecutes la app Streamlit
# Si ejecutas en Colab, la ruta del drive montado es correcta.
# Si ejecutas localmente, ajusta la ruta según donde hayas guardado los archivos.
base_path = '/content/drive/MyDrive/Despliegue Clasificacion'

# Construir las rutas completas a los archivos
onehot_encoder_path = os.path.join(base_path, 'onehot_encoder.joblib')
minmax_scaler_path = os.path.join(base_path, 'minmax_scaler.joblib')
model_path = os.path.join(base_path, 'best_knn_model.joblib')


# --- Cargar los modelos y scalers ---
@st.cache_resource
def load_resources():
    try:
        onehot_encoder = joblib.load(onehot_encoder_path)
        minmax_scaler = joblib.load(minmax_scaler_path)
        model = joblib.load(model_path)
        return onehot_encoder, minmax_scaler, model
    except FileNotFoundError as e:
        st.error(f"Error al cargar un archivo. Asegúrate de que los archivos .joblib estén en la ruta correcta: {e}")
        return None, None, None
    except Exception as e:
        st.error(f"Ocurrió un error al cargar los recursos: {e}")
        return None, None, None

onehot_encoder, minmax_scaler, model = load_resources()

# Verificar si los recursos se cargaron correctamente
if onehot_encoder is None or minmax_scaler is None or model is None:
    st.stop() # Detiene la ejecución de la aplicación si no se cargaron los recursos


# --- Título de la aplicación ---
st.title("Aplicación de Predicción")

st.write("Esta aplicación predice el resultado basado en las características de entrada.")

# --- Interfaz de usuario para la entrada de datos ---
st.header("Ingresa los datos:")

# Entrada para la variable categórica 'Felder'
felder_options = ['activo', 'visual', 'equilibrio', 'intuitivo', 'reflexivo', 'secuencial', 'sensorial', 'verbal'] # Asegúrate de que estas opciones coincidan con las categorías usadas en el entrenamiento
selected_felder = st.selectbox("Selecciona el tipo de Felder:", felder_options)

# Entrada para la variable numérica 'Examen_admisión'
examen_admision_value = st.number_input("Ingresa el valor de Examen de Admisión:", min_value=0.0, max_value=10.0, value=5.0, step=0.01) # Ajusta min/max/value según tus datos


# --- Botón para realizar la predicción ---
if st.button("Realizar Predicción"):
    # --- Preprocesamiento de los datos de entrada ---

    # Crear un DataFrame con los datos de entrada del usuario
    input_data = pd.DataFrame({
        'Felder': [selected_felder],
        'Examen_admisión': [examen_admision_value]
    })

    try:
        # Aplicar One-Hot Encoding a 'Felder'
        # Need to handle potential unseen categories during prediction
        try:
            felder_encoded = onehot_encoder.transform(input_data[['Felder']])
            if hasattr(felder_encoded, 'toarray'):
                felder_encoded_array = felder_encoded.toarray()
            else:
                felder_encoded_array = felder_encoded

            if hasattr(onehot_encoder, 'get_feature_names_out'):
                encoded_column_names = onehot_encoder.get_feature_names_out(['Felder'])
            elif hasattr(onehot_encoder, 'categories_'):
                 encoded_column_names = [f'Felder_{cat}' for cat in onehot_encoder.categories_[0]]
            else:
                 encoded_column_names = [f'Felder_encoded_{i}' for i in range(felder_encoded_array.shape[1])]

            df_felder_encoded_input = pd.DataFrame(felder_encoded_array, columns=encoded_column_names)

        except ValueError as e:
             st.error(f"Error en el One-Hot Encoding: Es posible que la categoría '{selected_felder}' no fuera vista durante el entrenamiento. {e}")
             st.stop() # Detiene la ejecución si hay una categoría no vista


        # Aplicar MinMax Scaling a 'Examen_admisión'
        examen_admision_scaled_input = minmax_scaler.transform(input_data[['Examen_admisión']])
        df_examen_admision_scaled_input = pd.DataFrame(examen_admision_scaled_input, columns=['Examen_admisión_Universidad_scaled']) # Usar el nombre de columna esperado por el modelo

        # Combinar las características preprocesadas
        # Asegurarse de que el orden de las columnas coincida con el entrenamiento del modelo
        # Esto es crucial. Una forma es crear un DataFrame con todas las columnas esperadas y llenarlo.
        # Obtener los nombres de las columnas esperadas por el modelo desde el encoder y la columna escalada
        expected_columns = list(encoded_column_names) + ['Examen_admisión_Universidad_scaled']

        # Crear un DataFrame vacío con las columnas esperadas
        df_processed_input = pd.DataFrame(0, index=[0], columns=expected_columns)

        # Llenar el DataFrame con los datos codificados y escalados
        for col in df_felder_encoded_input.columns:
            if col in df_processed_input.columns:
                df_processed_input[col] = df_felder_encoded_input[col].values[0]

        df_processed_input['Examen_admisión_Universidad_scaled'] = df_examen_admision_scaled_input['Examen_admisión_Universidad_scaled'].values[0]


        # Asegurarse de que el orden final de las columnas coincida exactamente con el entrenamiento del modelo
        # Si tienes el DataFrame de entrenamiento original o una lista de los nombres de las columnas en el orden correcto, úsala aquí.
        # Por ahora, asumiré el orden basado en las columnas generadas, lo cual puede no ser robusto.
        # Una mejor práctica sería guardar y cargar la lista de nombres de columnas del entrenamiento.
        # Por simplicidad, usaremos el orden generado aquí. Si el modelo falla, esta podría ser la causa.
        # Si tienes el DataFrame 'df_processed' del notebook con el orden correcto, puedes obtener los nombres así:
        # expected_column_order = df_processed.columns.tolist()
        # df_processed_input = df_processed_input[expected_column_order]


        # --- Realizar la predicción ---
        prediction = model.predict(df_processed_input)

        # --- Mostrar el resultado de la predicción ---
        st.header("Resultado de la Predicción:")

        # Interpretar la predicción (ajusta esto según el significado de 0 y 1 en tu modelo)
        if prediction[0] == 1:
            st.success("La predicción es: Sí (1)") # Ajusta la interpretación
        else:
            st.info("La predicción es: No (0)") # Ajusta la interpretación

    except Exception as e:
        st.error(f"Ocurrió un error durante el preprocesamiento o la predicción: {e}")

# --- Instrucciones para ejecutar la aplicación ---
st.markdown("""
Para ejecutar esta aplicación Streamlit:
1. Guarda el código anterior en un archivo Python (por ejemplo, `app.py`).
2. Abre una terminal en la ubicación donde guardaste el archivo.
3. Ejecuta el comando: `streamlit run app.py`
""")